### ISSUE TITLE
Create 2nd Version of User Flow for "Taking an Exam" Process

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#117]
# Story

As team InZone A we need to create a 2nd version of the User Flow "Taking an Exam", such that we refine the sequence of steps the user takes to complete the task within the product.

# Output
We want a User flow on diagrams.net

https://app.diagrams.net/#G1wAjoTPfk3QEq_o3aVrMT6WNwvzjgugjF

# Review process
User Flow shared on slack.

# Acceptance criteria

**Comment by ebaumhofer** [comment]
Looks like a great flow to me. I left one small comment on the diagram and will move this task to complete.
