### ISSUE TITLE
Low-Fidelity Prototype for "Taking an Exam"

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#118]
# Story

As team InZone A we need to create a Low-Fidelity Prototype as an early sample of our product such that we can elicit feedback from users by having them interact directly with the prototype.

# Tasks
- [x] #138
- [x] #139
- [x] #150 
- [x] #140
- [x] #141

# Output
We want a low-fidelity prototype.

# Review process
Prototype shared on slack and discussed with team

# Acceptance criteria
Follow-up questions by team answered

**Comment by etters** [comment]
task #142 moved to #161

**Comment by etters** [comment]
Prototype presented at sprint meeting 5/11
