### ISSUE TITLE
Discussing offline/online app behavior

### ISSUE THREAD

**Issue by etters** [WomenPlusPlus/deploy-impact-21-inzone-a#149]

**Comment by encima** [comment]
Link to Slack thread: https://inzonea.slack.com/archives/C02LBKMPA0Y/p1635855167005700

My thoughts: 

- Database should be source of truth for exams, app should be able to work online and offline
- Using Parse? https://inzone-a-parse-dashboard.tools.deployimpact.ch/ will allow easy adding of data and definition of schema
- Within that, this official library (alpha) can help to provide offline support without having to implement sync functionality: https://www.npmjs.com/package/@parse/react-native
- This allows you to focus on the UI and "business logic" and not so much on the implementation of syncing/handling offline things

**Comment by bkty** [comment]
To put everything a bit together:
* Parse => backend (where we store data: exams -new or completed- and feedbacks)
* Alpha-library => deals with uploading/downloading data from Parse to the App(Async Storage) when there is an internet connection - basically sync App with Parse, correct? 
* Async Storage => stores data when app is offline and then upload them/download new ones through alpha  when a connection is detected 

Did I get it right?

In what format should data be for upload/download from Parse?

**Comment by etters** [comment]
Discussion in meeting on 5/11, implementation continued in sprint 4.
