### ISSUE TITLE
User flow "admins uploading exams" v.2

### ISSUE THREAD

**Issue by etters** [WomenPlusPlus/deploy-impact-21-inzone-a#166]
continued from #169 

https://drive.google.com/drive/u/3/folders/1h9mNR5-jOdsRna1mmpbkoyY83qg8M1UO

**Comment by etters** [comment]
started in sprint 3

**Comment by ebaumhofer** [comment]
Didn't have time to get to this. Will need to move to Sprint 5.

**Comment by ebaumhofer** [comment]
@Fotini-Handra I updated the Coordinator upload exam flow. Can you give notes on this, please? Thanks. https://app.diagrams.net/#G1NSB4vmIolXEm6FAUZbaEsP0Gp3ttZFzj

**Comment by Fotini-Handra** [comment]
Hi Emma, 

I think we can close this task. I did a prototype for the coordinator dashboard and we will update it according to the PO feedback. Most of the steps in this Flow are included. I will update you further on Slack :)
