### ISSUE TITLE
Recruit proxy users

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#168]
As team InZone A we need to recruit users that resemble our target audience test.

**Comment by Fotini-Handra** [comment]
1/5 Usability Test sheculed by Fotini for the 12th of November at 20.30

**Comment by Fotini-Handra** [comment]
2/5 Usability Test sheculed by Fotini for the 14th of November at 16.00

**Comment by Fotini-Handra** [comment]
3/5 Usability Test scheduled by Maureen for the 11th of November

**Comment by Fotini-Handra** [comment]
2/5 Usability Test sheculed by Fotini for the 12th of November at 20.30

**Comment by Fotini-Handra** [comment]
3/5 Usability Test scheduled by Fotini for the 14th of November at 16.00

**Comment by ebaumhofer** [comment]
4/5 conducted by Emma on Nov 12th 
5/5 scheduled by Emma for Nov 13th
