### ISSUE TITLE
Conducting Usability Tests

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#173]
As team InZone A we need to conduct effective Usability Tests by staying as hands off as possible such that we can observe our product in action.

**Comment by Fotini-Handra** [comment]
1/5 Usability Test conducted by Fotini on the 12th of November 2021 at 20.30

**Comment by Fotini-Handra** [comment]
2/5 Usability Test conducted by Maureen on the 11th of November

**Comment by Fotini-Handra** [comment]
2/5 Usability Test conducted by Fotini on the 12th of November 2021 at 20.30

**Comment by ebaumhofer** [comment]
2/5 Usability test conducted by Emma on 12th November 2021. Notes: https://docs.google.com/document/d/1TcLBTBsqjkMBWFnmdM3_dw_0XH0am0Ec/edit

**Comment by Fotini-Handra** [comment]
4/5 Usability test postponed. We need first to revise the prototype according to the feedback received from the Product Owner.

**Comment by ebaumhofer** [comment]
I will close this task and we can open a new one for phase 2 of testing if we decide to do that.
