### ISSUE TITLE
Decide which software to use 

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#178]
As team InZone A we need to research which software we can use for our remote usability tests such that our test users can share their screen while we can record the whole session.

**Comment by Fotini-Handra** [comment]
We decided to use Jitsi Meet.

**Comment by Fotini-Handra** [comment]
Emma could you please find out how to send a calendar invite?

**Comment by ebaumhofer** [comment]
Hi Fotini. I tested Jitsi on Agorize and we can invite outsiders into our workspace. So you can start the video and get the link to share. If you want to schedule in a calendar, I would use Google Calendar and then remove the Google Meet link and add the Agorize Jitsi link. The only thing would be to make sure that others won't be using the room at the same time but I guess we don't use it so often.

**Comment by ebaumhofer** [comment]
You can also use Jitsi directly if you want https://meet.jit.si/ but I think I'll do the option described above. You just need to login to a dropbox account to have somewhere to save the recorded call. I created an account from within Agorize jitsi meeting in just a couple minutes.
